name: scooti
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.23.5
  - pandas=1.5.3
  - scikit-learn=1.1.3
  - numba=0.56.4
  - tqdm
  - cobra=0.26.3
  - scanpy=1.9.5
  - seaborn=0.12.2
  - phate=1.0.11
  - adjusttext=0.8
  - pytorch=2.0.1
  - pip
  - pip:
      - torch

